server:
  port: 8080
  servlet:
    context-path: /activityApi
  connection-timeout: 30000
spring:
#  数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.tmocloud.com:3306/payroll-data?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: ssg
    password: chuheridang5@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  activiti:
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
